# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ecfb02db734903a7a85127acb3cf39d480e9961e728643518b7224a02de94ce8794e7f60d0ac2d6b73191fd38ee6c2d5d4a523e01c116e46f271a4475b56088

test:
  secret_key_base: 0d8dc442f05c2a720ea23ce56fde345d689d5cfceed3bf1f5c1b6ba24795b6d8acb567029b16abc8ae139d5fba0e5a6ff312aa512015a681951e943fdb5c526c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
